const VERIFICATION_PAGE_URL = `${APPLICATION_HOSTING_SCHEME}://${APPLICATION_HOST}${APPLICATION_PORT}${APPLICATION_PATH}/verification-page`;


module.exports = {
  APPLICATION_NAME,
  APPLICATION_HOSTING_SCHEME,
  APPLICATION_HOST,
  APPLICATION_PORT,
  APPLICATION_PATH,
  VERIFICATION_PAGE_URL,
  VERIFICATION_TIMEOUT_MINUTES,
};
